### ISSUE TITLE
Parsing issue when field data is not identical to source data

### ISSUE THREAD

**Issue by kandyman2017** [javdejong/nhk-pronunciation#10]
I tried a bulk-add of pronunciations and noticed a lot of gaps. So I checked several of the missing words and found that the pitch/accent data was actually in the source data file, but in a slightly different format. For example, the bulk-add failed to generate data for 民間 because it was listed as 民間の in my collection. Likewise, if a noun has する attached to it, no pitch/accent will be added. For example, 公約する was also empty in my collection because only 公約 was listed in the source data. Unless the word in the Expression field matches **exactly** the word in the source file, it will not write to it. This is not optimal, in my opinion, because so many Japanese words are listed with things like する attached.

Is there a way to get the add-on to write to the Pronunciation field anyway by ignoring commonly appended words like する, の, な, etc?

**Comment by kandyman2017** [comment]
One more suggestion I have is to simply include the PA number instead of lines/arrows. PA is indicated by number 0-5 in most Japanese dictionaries, and I think that data is also in the repository here. Would it be possible to do a bulk add of just those numbers to any term matching an Anki note? Or would the same problem of ignoring non-identical terms apply here too?

**Comment by olety** [comment]
This is just a suggestion, but you could add another field with the dictionary form of the word to your card model and have the add-on look up words in that field.
<img width="755" alt="2018-03-30 1 06 04" src="https://user-images.githubusercontent.com/2990542/38134374-664a3f9a-341b-11e8-911a-8496692d697d.png">

**Comment by kandyman2017** [comment]
I don't understand how to do that. How can I bulk-add dictionary forms of verbs in a new field? There are over 20,000 notes in my collection.

**Comment by olety** [comment]
Yeah, idk whether you can bulk-add them, sorry. But it'll fix the problem going forward.

**Comment by SpongebobSquamirez** [comment]
I've fixed this problem (and a number of others) for most use cases in my new pull request. If it's a conjugation, that's a different story, though. If it's just particles or phrases, though, it'll work now if you use the new code (and hopefully it gets merged soon).

**Comment by javdejong** [comment]
Closing this as #18 has been merged.
