### ISSUE TITLE
Not working after newest update.

### ISSUE THREAD

**Issue by Kosezu** [javdejong/nhk-pronunciation#19]
I installed the most recent update from the anki add-on page and not it has stopped working. Pronunciation field no longer filled in. Same settings as before. I triked deleting everything and then reinstalling, but it did not work.

**Comment by SpongebobSquamirez** [comment]
What version of Anki do you have?

**Comment by mjuzikfrik** [comment]
Could it be due to the fact that the number on the addon page downloads Japanese Example Sentences addon and not Japanese Pitch? Javdejong probably changed the contents of the addon by mistake.

**Comment by javdejong** [comment]
Wow, you're totally right. One more reason I don't like the manual uploading process. Will fix it right now!

EDIT:
Thanks @mjuzikfrik for noticing this. Now fixed.
