### ISSUE TITLE
Question: What does the asterisk mean?

### ISSUE THREAD

**Issue by p2635** [javdejong/nhk-pronunciation#24]
I've started using this addon today but I don't understand what the asterisks are. I can probably work out the rest like the overline (since javdejong has documented this in the add on page), but can someone tell me what this is?

For example: オイシイ *** オイシꜜイ

**Comment by p2635** [comment]
Another question, I also saw that it colours some stuff in blue too, can you let me know what that means?? thanks

**Comment by javdejong** [comment]
It's just a separator between multiple possible pronunciations. 

As far as the blue color is concerned, see the explanation at https://ankiweb.net/shared/info/932119536 :

- Overline: Indicates "High" pitch (see "Binary pitch" in Wikipedia article)
- Downfall arrow: usually means stressing the mora/syllable before.
- Red circle mark: Nasal pronunciation、e.g. げ would be a nasal け.
- Blue color: barely pronounced at all. For example, a blue ヒ would be closer to "h" than "hi". Likewise, a blue ク would be more like a "k" than "ku".

**Comment by p2635** [comment]
Thanks for your input @javdejong , then do you usually learn the first pronunciation or the one that follows? how do I decide which one to learn?
