### ISSUE TITLE
Bug: mistake in nasalsoundpos in accent file

### ISSUE THREAD

**Issue by dudanian** [javdejong/nhk-pronunciation#26]
I found what I believe is a mistake in the accent file on entries 29138 and 29139. The midashigo1 コーキョーカンケンカクオ seems to have nasal sounds on pos 8 and 10, which would result in the nasalsoundpos value of 8010, but the actual value in the file is 810. So the nasal sounds aren't generated properly on this word.

**Comment by SpongebobSquamirez** [comment]
Hi, I hate to say it, but this addon is now obsolete. A much better addon in every way can be found here: https://ankiweb.net/shared/info/278530045 with links to its github and documentation. It originally took some ideas from this addon, and apparently took some code from the Japanese support addon, and has been thoroughly tested by many, including myself, so you can trust that it's better than this. It's free ofc so I encourage you to give it a try.

**Comment by dudanian** [comment]
That's a shame.
