### ISSUE TITLE
Doesn't supply a pitch for common words

### ISSUE THREAD

**Issue by scaryslender18** [javdejong/nhk-pronunciation#4]
For some reason, アメリカ, イギリス, and オーストラリア don't give any pitch accent. These are really common words, so why isn't it giving any pitch?

**Comment by javdejong** [comment]
It does not give a pitch for them, because it cannot find an entry in the [database](https://raw.githubusercontent.com/javdejong/nhk-pronunciation/master/ACCDB_unicode.csv). I do not know why NHK did not include them in the past, but maybe they do now.
