### ISSUE TITLE
Change of the markings

### ISSUE THREAD

**Issue by mjuzikfrik** [javdejong/nhk-pronunciation#5]
Hello,

Is there a way to make the plugin change the way it marks the accent? 
I would like to have it like it is ine the newest edition of the dictionary. I've made it to display the slash for marking the drop in pitch but can't get it to show the upper line after the word when it's heiban.

https://www.nhk-book.co.jp/assets_item/000000113452016/sub_accent.png

**Comment by javdejong** [comment]
https://github.com/javdejong/nhk-pronunciation/blob/master/nhk_pronunciation.py#L26

You can change the entry for ''''&#42780;'''' to be a colored backslash-like character. For the "horizontal" line you probably need to change the overline logic in these lines: https://github.com/javdejong/nhk-pronunciation/blob/master/nhk_pronunciation.py#L117

**Comment by javdejong** [comment]
In Anki 2.1 you can now do this in the config.json (from the Anki UI). You can change the mapping `"&#42780;": "&#42780;"` to something like `"&#42780;": "<span style="color: red">\</span>"`
