### ISSUE TITLE
Error message on installation

### ISSUE THREAD

**Issue by epistularum** [javdejong/nhk-pronunciation#9]
I get an error message when I reopen anki after installing the addon

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "C:\Users\yuri-lucas\AppData\Roaming\Anki2\addons\nhk_pronunciation.py", line 14, in <module>
    import japanese
ImportError: No module named japanese

**Comment by jlloyola** [comment]
You need to install the [Japanese Support Add-on](https://ankiweb.net/shared/info/3918629684). The error will go away after that.

**Comment by epistularum** [comment]
I'm dumb thanks a lot!
